function [fitresult, gof] = HisExpFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Feb-2018 08:21:48


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0];
l=length(x);
mu_guess=log(y(end)/y(round(l/2)))./(x(end)-x(round(l/2)));
opts.StartPoint = [x(1) mu_guess];
opts.Upper = [max(y)*1.05 4*mu_guess];
indtmp=find(yData>max(yData)/4,1);
indtmp=max(round(l/2),indtmp);
xData=xData(indtmp:l);
yData=yData(indtmp:l);
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel x
%ylabel y
%grid on


