function [fitresult, gof] = MyExpFit(x,y)
%CREATEFIT(T,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Feb-2019 02:40:15
%% Fit: 'to exponential function'.
[xData, yData] = prepareCurveData(x,y);

% Set up fittype and options.
ft = fittype( '(x>T)*a*exp(b*x)+(x<T)*1', 'independent', 'x', 'dependent', 'y' );%
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
mu0 = log(y(end)/y(1))/(x(end)-x(1));
a0 = 1;
T0 = 0;
%             Tr  a  mu
opts.Lower = [0   0 -Inf];
opts.Upper = [Inf Inf Inf];
opts.StartPoint = [T0 a0 mu0];%[0.1 0.1 1];
% opts.Lower = [0 -Inf];% [a Treshold mu]
% opts.Upper = [Inf Inf];
% opts.StartPoint = [a0 mu0];


% Fit model to data.
[fitresult, gof] = fit(xData, yData, ft, opts);

% Plot fit with data.
%fh = figure( 'Name', 'Exponential Fit' );
%ax1 = axes(fh);
%h = plot(fitresult, xData, yData );
%legend( h, 'y vs. x', 'My Personal Fit', 'Location', 'NorthEast' );
%set(ax1,'xlim',[0 500],'ylim',[0 500]);
% Label axes
%xlabel x
%ylabel y
%grid on
